version:            '2'
services:
  cc:
    container_name:
      "cc"
    build:
      context:      ./cc
    image:
      "cc"
    command:        node index.js
    ports:
      - "3000:3000"
    depends_on:
      - data
    restart: unless-stopped
  ph:
    container_name:
      "ph"
    build:
      context:      ./ph
    image:
      "ph"
    command:        node index.js
    ports:
      - "3002:3002"
    depends_on:
      - data
    restart: unless-stopped
  client:
    container_name:
      "client"
    build:
      context:      ./client
    image:
      "client"
    command:        ng serve --host 0.0.0.0 --public 192.168.99.100:8085
    ports:
      - "8085:8085"
    restart: unless-stopped
  mi:
    container_name:
      "mi"
    build:
      context:      ./mi
    image:
      "mi"
    command:        node index.js
    ports:
      - "3001:3001"
    depends_on:
      - data
    restart: always
  data:
    image:          mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
